repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [fix, feat, docs, ci, chore] # optional: list of Conventional Commits types to allow e.g. [fix, feat, docs, ci, chore]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint-fix-docker
        name: markdownlint-fix-docker
        description: "Fixes the style of Markdown/Commonmark files."
        entry: ghcr.io/igorshubovych/markdownlint-cli --fix
        language: docker_image
        types: [markdown]
        minimum_pre_commit_version: 0.15.0
